import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const {chromium}=createRequire(import.meta.url)(process.env.AGENT_PLAYWRIGHT_MODULE||'playwright');
const {AGENT_UI_ORIGIN:origin,AGENT_UI_TEST_OUTPUT:output}=process.env;
assert.ok(origin&&output);
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'});
const receiverContext=await browser.newContext({viewport:{width:1360,height:1000}}),issuerContext=await browser.newContext({viewport:{width:1360,height:1000}});
const receiver=await receiverContext.newPage(),issuer=await issuerContext.newPage();
const errors=[];
for(const page of [receiver,issuer]){page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(String(e)));}
const work=page=>page.getByRole('dialog',{name:'Agent 协作',exact:true});
const card=page=>work(page).locator('.peer-card').filter({has:page.getByRole('heading',{name:'专业核对',exact:true})});
const editor=()=>receiver.getByRole('dialog',{name:'配置 Agent',exact:true});
const login=async(page,email)=>{
 await page.goto(origin);
 await page.getByLabel('账号',{exact:true}).fill(email);
 await page.getByLabel('密码',{exact:true}).fill('Execution-Changed!26');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('button',{name:'Agent 协作 目录、委派与沟通',exact:true}).click();
 await work(page).getByRole('button',{name:'Agent 目录',exact:true}).click();
};
const edit=async()=>card(receiver).getByRole('button',{name:'配置',exact:true}).click();
const save=async()=>{
 const saved=receiver.waitForResponse(r=>r.url().includes('/agent/agents/')&&r.request().method()==='PUT');
 await editor().getByRole('button',{name:'保存 Agent',exact:true}).click();
 const response=await saved;
 assert.equal(response.status(),200,await response.text());
 const body=JSON.parse(response.request().postData());
 await editor().waitFor({state:'hidden'});
 return body;
};
try{
 await login(receiver,'admin@example.com');
 await edit();
 assert.equal(await editor().getByLabel('委派执行身份',{exact:true}).inputValue(),'caller');
 await editor().getByLabel('委派执行身份',{exact:true}).selectOption('owner');
 await editor().getByText('保存后绑定我当前选定的角色',{exact:true}).waitFor();
 const binding=await save();
 assert.equal(binding.delegation_execution,'owner');
 assert.equal(Object.hasOwn(binding,'delegation_role_key'),false);
 await login(issuer,'system_administrator@example.com');
 await card(issuer).getByText(/委派由所有者的 .+ 角色执行/).waitFor();
 assert.equal(await card(issuer).getByRole('button',{name:'配置',exact:true}).count(),0);
 await work(issuer).getByRole('button',{name:'委派与进度',exact:true}).click();
 await work(issuer).getByRole('button',{name:/^核对接收方的实际待办/}).first().click();
 await work(issuer).getByText('执行详情当前不可读取，委派状态和获准的交付仍可查看。',{exact:true}).waitFor();
 assert.equal(await work(issuer).getByRole('button',{name:'接收方会话',exact:true}).count(),0);
 assert.equal(await work(issuer).getByRole('button',{name:'查看实时执行与工具调用',exact:true}).count(),0);
 assert.equal(await work(issuer).getByRole('button',{name:'发起方会话',exact:true}).count(),1);
 assert.doesNotMatch(await work(issuer).innerText(),/RECEIVER-PRIVATE-PROFESSIONAL-TODO/);
 await work(issuer).getByRole('button',{name:'Agent 目录',exact:true}).click();
 await edit();
 const originalRole=await editor().getByText(/^已绑定角色：/).innerText();
 await editor().getByLabel('擅长的工作',{exact:true}).fill('按接收方保存的角色核对');
 const ordinary=await save();
 assert.equal(Object.hasOwn(ordinary,'delegation_execution'),false);
 await edit();
 assert.equal(await editor().getByText(/^已绑定角色：/).innerText(),originalRole);
 await editor().getByLabel('委派执行身份',{exact:true}).scrollIntoViewIfNeeded();
 await receiver.waitForFunction(()=>{const e=document.querySelector('.peer-editor');return e&&getComputedStyle(e).opacity==='1'&&e.getAnimations().every(a=>a.playState!=='running');});
 await receiver.screenshot({path:join(output,'execution-binding-editor.png'),fullPage:true});
 await receiver.setViewportSize({width:390,height:844});
 await editor().getByLabel('委派执行身份',{exact:true}).scrollIntoViewIfNeeded();
 await receiver.waitForFunction(()=>{const e=document.querySelector('.peer-editor');const r=e?.getBoundingClientRect();return r&&r.x>=0&&r.right<=innerWidth&&e.scrollWidth<=e.clientWidth+1;});
 await receiver.screenshot({path:join(output,'execution-binding-mobile.png'),fullPage:true});
 await editor().getByLabel('委派执行身份',{exact:true}).selectOption('caller');
 const disabled=await save();
 assert.equal(disabled.delegation_execution,'caller');
 await card(issuer).getByText(/按你的当前权限执行/).waitFor();
 await issuer.reload();
 await issuer.getByRole('button',{name:'Agent 协作 目录、委派与沟通',exact:true}).click();
 await work(issuer).getByRole('button',{name:'Agent 目录',exact:true}).click();
 await card(issuer).getByText(/按你的当前权限执行/).waitFor();
 assert.deepEqual(errors,[]);
 await writeFile(join(output,'execution-binding-report.json'),JSON.stringify({passed:true,realChrome:true,realIdentityUsers:true,scenarios:['bind authenticated selected role','shared directory states receiving identity','issuer cannot edit binding','ordinary edits preserve saved role','390px layout','disable owner execution persists after reload'],errors},null,2));
}catch(error){await receiver.screenshot({path:join(output,'receiver-failure.png'),fullPage:true});await issuer.screenshot({path:join(output,'issuer-failure.png'),fullPage:true});throw error;}
finally{await browser.close();}
