import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const {chromium}=createRequire(import.meta.url)(process.env.AGENT_PLAYWRIGHT_MODULE||'playwright');
const origin=process.env.AGENT_UI_ORIGIN,output=process.env.AGENT_UI_TEST_OUTPUT;
assert.ok(origin&&output);await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1360,height:1000}});page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
const work=()=>page.getByRole('dialog',{name:'Agent 协作',exact:true});
const change=async profile=>{const r=await page.request.post(origin+'/fixture/collaboration-permissions?profile='+profile);assert.equal(r.status(),204);};
try {
 await page.goto(origin+'#'+process.env.AGENT_UI_CONVERSATION);
 await page.getByLabel('账号',{exact:true}).fill('admin@example.com');await page.getByLabel('密码',{exact:true}).fill('Peer-Changed!33');await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('button',{name:'Agent 协作 目录、委派与沟通',exact:true}).click();
 await work().getByRole('button',{name:'查看交付与验收历史',exact:true}).click();
 await work().getByRole('list',{name:'交付与验收历史',exact:true}).waitFor();
 await work().getByRole('button',{name:'查看实时执行与工具调用',exact:true}).click();
 const run=page.getByRole('dialog',{name:'处理记录',exact:true});await run.waitFor();
 await change('view');await run.waitFor({state:'hidden'});
 await work().getByRole('region',{name:'交付完成条件核对',exact:true}).waitFor({state:'hidden'});
 assert.equal(await work().getByRole('list',{name:'交付与验收历史',exact:true}).count(),0);
 assert.equal(await work().getByRole('region',{name:'委派通信',exact:true}).count(),0);
 assert.equal(await work().getByRole('button',{name:'暂停',exact:true}).count(),0);
 assert.doesNotMatch(await work().innerText(),/独立核查完成|核查口径已确认/);
 await page.screenshot({path:join(output,'peer-permissions-metadata.png'),fullPage:true});
 await change('delivery');
 await work().getByText('独立核查完成',{exact:true}).waitFor();
 assert.equal(await work().getByRole('button',{name:/查看实时执行|查看执行证据|查看第.*原回执/}).count(),0);
 assert.equal(await work().getByRole('button',{name:'核对交付',exact:true}).count(),0);
 await work().getByRole('button',{name:'查看交付与验收历史',exact:true}).click();
 await work().getByRole('list',{name:'交付与验收历史',exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.waitForFunction(()=>{const el=document.querySelector('.collaboration-dialog');const r=el?.getBoundingClientRect();return r&&r.x>=0&&r.right<=innerWidth&&el.scrollWidth<=el.clientWidth+1;});
 await work().getByRole('region',{name:'交付完成条件核对',exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:join(output,'peer-permissions-delivery-mobile.png'),fullPage:true});
 await page.setViewportSize({width:1360,height:1000});
 await change('manage');await work().getByRole('button',{name:'暂停',exact:true}).click();
 await work().getByLabel('原因与处理意见',{exact:true}).fill('权限撤回后此表单必须关闭');
 await change('view');await work().getByLabel('原因与处理意见',{exact:true}).waitFor({state:'hidden'});
 await change('none');await work().getByRole('button',{name:'启用管理员协作权限',exact:true}).waitFor();
 assert.equal(await work().getByRole('button',{name:'核查当前权限',exact:true}).count(),0);
 const access=await page.evaluate(async()=>{const session=await (await fetch('/app/session')).json();return(await fetch('/agent/collaboration-access',{headers:{'X-Agent-Scope':session.scope}})).json();});
 assert.equal(access.allowed?.length||0,0);
 await work().getByRole('button',{name:'启用管理员协作权限',exact:true}).click();
 await work().getByRole('button',{name:'查看实时执行与工具调用',exact:true}).waitFor();
 assert.deepEqual(errors,[]);
 await writeFile(join(output,'permissions-report.json'),JSON.stringify({passed:true,realChrome:true,realIdentityRoleEdits:true,scenarios:['revocation closes open run and delivery history','metadata omits execution delivery and communication','delivery reader without execution permission','revocation closes pending management form','administrator setup is explicit'],errors},null,2));
} catch(error) {await page.screenshot({path:join(output,'permissions-failure.png'),fullPage:true});throw error;}
finally {await browser.close();}
