import {useEffect,useState} from 'react';
import {request} from './api.ts';
import {describeError} from './errors.ts';
import type {ConversationTaskDetail} from './task-state.ts';
import {Button} from './components/ui/button';
import {Input} from './components/ui/input';

type Access={allowed?:string[]};
type Feedback={id:string;outcome:'adopted'|'revised'|'failed';uncertainty?:string;agent_id:string;agent_revision:number;agent_prompt_version:string;target_skill_keys?:string[];skill_versions?:Record<string,string>};

const outcomeLabel={adopted:'成果已采用',revised:'成果经过修改',failed:'任务结果未采用'} as const;

export function CapabilityFeedback({task}:{task:ConversationTaskDetail}){
 const skillEntries=Object.entries(task.skill_versions||{});
 const [enabled,setEnabled]=useState(false),[outcome,setOutcome]=useState<Feedback['outcome']>(task.status==='failed'?'failed':'adopted'),[reason,setReason]=useState(''),[uncertainty,setUncertainty]=useState(''),[artifact,setArtifact]=useState(''),[skillKeys,setSkillKeys]=useState<string[]>(skillEntries.length===1?[skillEntries[0][0]]:[]),[receipt,setReceipt]=useState<Feedback|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController();request<Access>('/agent/collaboration-access','GET',undefined,controller.signal).then(value=>{if(!controller.signal.aborted)setEnabled(!!value.allowed?.includes('configure'));}).catch(()=>{if(!controller.signal.aborted)setEnabled(false);});return()=>controller.abort();},[]);
 if(!enabled||!task.execution_run_id||!['awaiting_review','completed','failed','cancelled'].includes(task.status))return null;
 async function submit(){if(!reason.trim()||busy)return;setBusy(true);setError('');try{const selected=task.artifacts.find(item=>`${item.id}:${item.version}`===artifact);const value=await request<Feedback>('/agent/capability-feedback','POST',{client_id:crypto.randomUUID(),task_id:task.id,outcome,reason:reason.trim(),uncertainty:uncertainty.trim(),skill_keys:skillKeys,...(selected?{artifact_id:selected.id,artifact_version:selected.version}:{})});setReceipt(value);}catch(failure){setError(describeError(failure));}finally{setBusy(false);}}
 return <section className="skill-detail" aria-label="任务结果反馈"><div className="task-detail-heading"><h4>记录能力反馈</h4><span>Agent {task.agent_id} · {task.agent_prompt_version}</span></div>{receipt?<><p role="status">已记录：{outcomeLabel[receipt.outcome]}</p><small className="subtle">反馈 {receipt.id} · Agent {receipt.agent_id} · {receipt.agent_prompt_version}{receipt.target_skill_keys?.length?` · 指向 ${receipt.target_skill_keys.map(key=>`${key}@${receipt.skill_versions?.[key]||'未知版本'}`).join('、')}`:' · 指向 Agent 整体'}{receipt.uncertainty?` · 限制：${receipt.uncertainty}`:''}</small></>:<><p className="subtle">记录成果是否采用以及修改或失败原因。这里显示并提交任务冻结的实际配置；只有明确勾选的 Skill 才能成为该 Skill 改进候选的依据。</p><div className="todo-toolbar"><select aria-label="任务反馈结果" value={outcome} onChange={event=>setOutcome(event.target.value as Feedback['outcome'])}>{Object.entries(outcomeLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{!!task.artifacts.length&&<select aria-label="关联成果版本" value={artifact} onChange={event=>setArtifact(event.target.value)}><option value="">不关联具体成果</option>{task.artifacts.map(item=><option key={`${item.id}:${item.version}`} value={`${item.id}:${item.version}`}>{item.title} · 版本 {item.version}</option>)}</select>}</div>{!!skillEntries.length&&<fieldset><legend>反馈涉及的 Skill（可不选，表示 Agent 整体）</legend>{skillEntries.map(([key,version])=><label key={key}><input type="checkbox" checked={skillKeys.includes(key)} onChange={event=>setSkillKeys(current=>event.target.checked?[...current,key]:current.filter(item=>item!==key))}/>{key} · {version}</label>)}</fieldset>}<Input aria-label="反馈原因" value={reason} maxLength={4096} placeholder={outcome==='revised'?'说明修改了什么以及原因':outcome==='failed'?'说明未采用或失败的原因':'说明采用的依据'} onChange={event=>setReason(event.target.value)}/><Input aria-label="反馈适用限制" value={uncertainty} maxLength={1024} placeholder="可选：样本不足、仅适用于本任务或仍待核实的部分" onChange={event=>setUncertainty(event.target.value)}/><Button size="sm" disabled={busy||!reason.trim()} onClick={()=>void submit()}>保存反馈</Button></>}{error&&<p role="alert" className="text-destructive">{error}</p>}</section>;
}
