import { useEffect, useRef, useState } from 'react';
import { formatLocalDateTime } from './time.ts';
import { request } from './api.ts';
import { describeError } from './errors.ts';
import { Button } from './components/ui/button';
import { Input } from './components/ui/input';
import { disagreementLabel, disagreementNeedsReview, peerPath, type Delegation, type DisagreementClaimInput, type DisagreementDecision, type DisagreementHistory, type DisagreementRecord, type EvidenceComparison } from './collaboration-state.ts';
import type { ResultReference } from './execution-state.ts';

const emptyClaim=():DisagreementClaimInput=>({conclusion:'',data_scope:'',period:'',source_version:'',calculation:'',receipts:[]});
const emptyComparison=():EvidenceComparison=>({data_scope:'',period:'',source_version:'',calculation:''});
const fields=[['data_scope','数据范围'],['period','时间范围'],['source_version','来源及版本'],['calculation','计算或推导过程']] as const;
const outcomeLabels:Record<string,string>={inspect:'补查证据',revise:'修订结论',ask_user:'请用户判断',adopt:'采用结论'};
const referenceKey=(r:ResultReference)=>`${r.conversation_id}:${r.run_id}:${r.step}:${r.call_id}:${r.sha256}`;

function evidenceChoices(d:Delegation,record?:DisagreementRecord){
 const choices=new Map<string,{ref:ResultReference;label:string}>();
 const add=(ref:ResultReference,label:string)=>choices.set(referenceKey(ref),{ref,label});
 for(const step of d.task?.steps||[])for(const call of step.calls)if(call.result_reference)add(call.result_reference,`第 ${step.number+1} 步 · ${call.name} · ${call.status}`);
 for(const effect of d.handoff?.effects||[])add(effect.reference,`${effect.tool} · 原操作回执`);
 for(const check of d.verification?.checks||[])for(const ref of check.receipts||[])add(ref,`完成条件 ${check.condition+1} · ${ref.call_id}`);
 for(const claim of record?.claims||[])for(const ref of claim.receipts||[])add(ref,`已有结论证据 · ${ref.call_id}`);
 return [...choices.values()];
}

function ClaimFields({index,value,onChange,choices}:{index:number;value:DisagreementClaimInput;onChange:(v:DisagreementClaimInput)=>void;choices:ReturnType<typeof evidenceChoices>}){
 return <fieldset><legend>结论 {index+1}</legend><label>结论<textarea aria-label={`结论 ${index+1} 内容`} required maxLength={2048} rows={2} value={value.conclusion} onChange={e=>onChange({...value,conclusion:e.target.value})}/></label>{fields.map(([key,label])=><label key={key}>{label}<textarea aria-label={`结论 ${index+1} ${label}`} required maxLength={key==='calculation'?2048:512} rows={2} value={value[key]} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>)}<details><summary>关联原回执（最多 4 项）</summary>{choices.length===0?<p>当前没有可选回执，可先补查证据；这里记录的结论仍需核对。</p>:choices.map(({ref,label})=>{const selected=(value.receipts||[]).some(r=>referenceKey(r)===referenceKey(ref));return <label key={referenceKey(ref)}><input type="checkbox" checked={selected} disabled={!selected&&(value.receipts?.length||0)>=4} onChange={e=>onChange({...value,receipts:e.target.checked?[...(value.receipts||[]),ref]:(value.receipts||[]).filter(r=>referenceKey(r)!==referenceKey(ref))})}/>{label}</label>;})}</details></fieldset>;
}

function RecordView({record,name,onRun}:{record:DisagreementRecord;name:(id:string)=>string;onRun?: (c:string,r:string)=>void}){
 const deciding=record.decision_actor||record.actor;
 return <><p>{record.reason}</p><div className="peer-disagreement-claims">{record.claims.map((claim,index)=><section className="task-result" key={claim.id}><h5>结论 {index+1} · {claim.conclusion}</h5><dl>{fields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{claim[key]}</dd></div>)}</dl><small>记录者：{claim.actor.agent_id?name(claim.actor.agent_id):claim.actor.user_id} · {formatLocalDateTime(claim.created_at)}</small>{onRun&&claim.receipts?.map(ref=><Button variant="ghost" key={referenceKey(ref)} onClick={()=>onRun(ref.conversation_id,ref.run_id)}>查看结论 {index+1} 原回执</Button>)}</section>)}</div>{record.decision&&<section aria-label="分歧处理决定"><h5>{outcomeLabels[record.decision.outcome]}</h5><p>{record.decision.basis}</p><dl>{fields.map(([key,label])=><div key={key}><dt>{label}对照</dt><dd>{record.decision!.comparison[key]}</dd></div>)}</dl>{record.decision.adopt_claim_id&&<p>采用：{record.claims.find(c=>c.id===record.decision!.adopt_claim_id)?.conclusion||'历史结论引用'}</p>}{record.next_action&&<p>后续：{record.next_action}</p>}{(record.owner_agent_id||record.owner_user_id)&&<p>负责方：{record.owner_agent_id?name(record.owner_agent_id):record.owner_user_id}</p>}<small>决定者：{deciding.agent_id?name(deciding.agent_id):deciding.user_id}</small>{onRun&&deciding.source&&<Button variant="ghost" onClick={()=>onRun(deciding.source!.conversation_id,deciding.source!.run_id)}>查看决定来源</Button>}</section>}</>;
}

type Edit={operation:'raise'|'add_claim'|'decide';delegation:Delegation;record?:DisagreementRecord};
function DisagreementEditor({edit,name,busy,onSubmit,onClose}:{edit:Edit;name:(id:string)=>string;busy:boolean;onSubmit:(change:Record<string,unknown>,reason:string,revision:number)=>Promise<boolean>;onClose:()=>void}){
 const d=edit.delegation,record=edit.record;
 const [title,setTitle]=useState(''),[condition,setCondition]=useState(''),[reason,setReason]=useState('');
 const [claims,setClaims]=useState<DisagreementClaimInput[]>(edit.operation==='raise'?[emptyClaim(),emptyClaim()]:[emptyClaim()]);
 const [decision,setDecision]=useState<DisagreementDecision>({outcome:'inspect',basis:'',comparison:emptyComparison(),owner_agent_id:d.to_agent_id,next_action:'',brief_version:d.brief.version,agreement_revision:d.agreement_revision||1,delivery_digest:d.delivery?d.verification?.delivery_digest||'':''});
 const choices=evidenceChoices(d,record);
 async function submit(e:React.FormEvent){e.preventDefault();const change:Record<string,unknown>={operation:edit.operation,...(record?{id:record.id,expected_revision:record.revision}:{title,...(condition!==''?{condition:Number(condition)}:{})}),...(edit.operation==='decide'?{decision}:{claims})};if(await onSubmit(change,reason,d.revision))onClose();}
 return <form className="peer-form" aria-label="结构化分歧表单" onSubmit={submit}><h5>{edit.operation==='raise'?'记录不同结论':edit.operation==='add_claim'?'补充结论与证据':'对照证据并决定'}</h5><p>依据当前需求 v{d.brief.version} / 约定 {d.agreement_revision||1}。不确定的资料请注明尚未核实。</p>{edit.operation==='raise'&&<><label>分歧主题<Input required maxLength={512} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>关联完成条件<select aria-label="关联完成条件" value={condition} onChange={e=>setCondition(e.target.value)}><option value="">整项工作</option>{d.brief.completion_conditions.map((c,i)=><option key={i} value={i}>{i+1}. {c}</option>)}</select></label></>}{edit.operation!=='decide'?claims.map((claim,i)=><ClaimFields key={i} index={i} value={claim} choices={choices} onChange={v=>setClaims(claims.map((c,j)=>j===i?v:c))}/>):<><p>请对照每个结论的证据；先后顺序和多数意见不能替代依据。</p><label>处理方式<select aria-label="分歧处理方式" value={decision.outcome} onChange={e=>setDecision({...decision,outcome:e.target.value,adopt_claim_id:undefined,owner_agent_id:['inspect','revise'].includes(e.target.value)?d.to_agent_id:undefined,next_action:e.target.value==='adopt'?undefined:''})}>{Object.entries(outcomeLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{fields.map(([key,label])=><label key={key}>{label}对照<textarea aria-label={`${label}对照`} required maxLength={1024} rows={2} value={decision.comparison[key]} onChange={e=>setDecision({...decision,comparison:{...decision.comparison,[key]:e.target.value}})}/></label>)}<label>采用或继续核对的依据<textarea aria-label="分歧处理依据" required maxLength={2048} rows={3} value={decision.basis} onChange={e=>setDecision({...decision,basis:e.target.value})}/></label>{decision.outcome==='adopt'?<label>采用的结论<select aria-label="采用的结论" required value={decision.adopt_claim_id||''} onChange={e=>setDecision({...decision,adopt_claim_id:e.target.value})}><option value="">选择已核对的结论</option>{record?.claims.map((c,i)=><option key={c.id} value={c.id}>{i+1}. {c.conclusion}</option>)}</select></label>:<>{decision.outcome!=='ask_user'&&<label>后续负责方<select aria-label="分歧后续负责方" value={decision.owner_agent_id||''} onChange={e=>setDecision({...decision,owner_agent_id:e.target.value})}>{[d.from_agent_id,d.to_agent_id].map(id=><option key={id} value={id}>{name(id)}</option>)}</select></label>}<label>{decision.outcome==='ask_user'?'需要用户判断的问题':'后续工作'}<textarea aria-label="分歧后续工作" required maxLength={1024} rows={3} value={decision.next_action||''} onChange={e=>setDecision({...decision,next_action:e.target.value})}/></label></>}</>}<label>本次记录说明<textarea aria-label="分歧记录说明" required maxLength={4096} rows={2} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="todo-toolbar"><Button type="submit" disabled={busy}>保存分歧记录</Button><Button type="button" variant="ghost" onClick={onClose}>收起表单</Button></div></form>;
}

export function Disagreements({value:d,name,busy,onMutate,onRun}:{value:Delegation;name:(id:string)=>string;busy:boolean;onMutate:(change:Record<string,unknown>,reason:string,revision:number)=>Promise<boolean>;onRun?: (c:string,r:string)=>void}){
 const [selected,setSelected]=useState(''),[history,setHistory]=useState<DisagreementHistory|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[edit,setEdit]=useState<Edit|null>(null);const generation=useRef(0),latest=useRef(d);latest.current=d;
 const visible=d.disagreements?.find(i=>i.id===selected),current=history?.items[0];
 async function load(id:string,before?:number){const requestID=++generation.current,delegationID=d.id,revision=d.disagreements?.find(i=>i.id===id)?.revision;setLoading(true);setError('');try{const page=await request<DisagreementHistory>(`${peerPath(d.id)}/disagreements/${encodeURIComponent(id)}${before?`?before_revision=${before}`:''}`);if(requestID!==generation.current||latest.current.id!==delegationID||!latest.current.disagreements?.some(i=>i.id===id&&i.revision===revision))return;setSelected(id);setHistory(previous=>before&&previous?{...page,items:[...previous.items,...page.items]}:page);}catch(e){if(requestID===generation.current){setHistory(null);setError(describeError(e));}}finally{if(requestID===generation.current)setLoading(false);}}
 useEffect(()=>{if(d.disagreements_omitted)setEdit(null);},[d.disagreements_omitted]);
 useEffect(()=>{if(selected&&!visible){generation.current++;setSelected('');setHistory(null);setEdit(null);setLoading(false);}else if(selected&&visible&&current&&visible.revision!==current.revision)void load(selected);},[visible?.revision,!!visible,selected]);
 return <section className="peer-dependencies" aria-label="结构化结论分歧"><h4>结论分歧</h4><p>按证据核对不同结论，保留决定和后续责任。未解决或旧版本的分歧会阻止验收。</p>{d.disagreements_omitted&&<p role="status">部分分歧来源当前不可访问，请先处理资料权限。</p>}<ul aria-label="结论分歧列表">{d.disagreements?.map(issue=><li key={issue.id}><strong>{issue.title} · {disagreementLabel[issue.status]||issue.status}</strong>{disagreementNeedsReview(issue,d)&&<p>要求或交付已变化，需按当前版本重新核对。</p>}{issue.requirement&&<p>关联条件：{issue.requirement}</p>}{issue.next_action&&<p>{issue.next_action}</p>}{(issue.owner_agent_id||issue.owner_user_id)&&<p>负责方：{issue.owner_agent_id?name(issue.owner_agent_id):issue.owner_user_id}</p>}<Button variant="ghost" disabled={loading} onClick={()=>{setEdit(null);void load(issue.id);}}>查看分歧证据与历史</Button></li>)}</ul>{d.access?.communicate&&!['cancelled','rejected'].includes(d.status)&&<Button variant="outline" disabled={busy} onClick={()=>setEdit({operation:'raise',delegation:d})}>记录结论分歧</Button>}{history&&current&&visible&&<section aria-label="分歧证据与历史"><h5>{current.title} · 修订 {current.revision}</h5><RecordView record={current} name={name} onRun={onRun}/>{!['cancelled','rejected'].includes(d.status)&&<div className="todo-toolbar">{d.access?.communicate&&<Button variant="outline" disabled={busy} onClick={()=>setEdit({operation:'add_claim',delegation:d,record:current})}>补充结论与证据</Button>}{d.access?.manage&&<Button variant="outline" disabled={busy} onClick={()=>setEdit({operation:'decide',delegation:d,record:current})}>对照证据并决定</Button>}</div>}{history.items.slice(1).map(record=><details key={record.revision}><summary>历史修订 {record.revision} · {disagreementLabel[record.status]} · {formatLocalDateTime(record.updated_at)}</summary><RecordView record={record} name={name} onRun={onRun}/></details>)}{!history.complete&&<Button variant="ghost" disabled={loading} onClick={()=>void load(selected,history.next_before)}>更早的分歧记录</Button>}</section>}{edit&&(edit.operation==='decide'?d.access?.manage:d.access?.communicate)&&<DisagreementEditor key={`${edit.operation}:${edit.delegation.revision}:${edit.record?.revision||0}`} edit={edit} name={name} busy={busy} onSubmit={onMutate} onClose={()=>setEdit(null)}/>} {error&&<p role="alert">{error}</p>}</section>;
}
