import { useState } from 'react';
import { sessionUserID } from './session.ts';
import { PeerDocumentPicker, PeerSharedDocuments, sharedDocumentReference } from './PeerDocumentShare';
import type { KnowledgeDocument } from './knowledge-document-state.ts';
import { Button } from './components/ui/button';
import { briefFieldLabel, isOpenQuestion, type Delegation } from './collaboration-state.ts';

export function PeerMessages({value:d,name,busy,onSend}:{value:Delegation;name:(id:string)=>string;busy:boolean;onSend:(body:Record<string,unknown>)=>Promise<boolean>}) {
 const [message,setMessage]=useState(''),[to,setTo]=useState(d.to_agent_id),[kind,setKind]=useState('message'),[deliveryMode,setDeliveryMode]=useState('next_step'),[replyTo,setReplyTo]=useState('');
 const [documents,setDocuments]=useState<KnowledgeDocument[]>([]);
 const reply=d.messages.find(m=>m.id===replyTo);
 async function send(e:React.FormEvent){e.preventDefault();if(await onSend({to_agent_id:to,content:message,brief_version:d.brief.version,agreement_revision:d.agreement_revision||1,kind,delivery_mode:deliveryMode,...(d.access?.share&&documents.length?{documents:documents.map(sharedDocumentReference)}:{}),...(kind==='reply'?{reply_to_id:replyTo}:{})})){setMessage('');setReplyTo('');setKind('message');setDocuments([]);}}
 const kinds:Record<string,string>={message:'消息',question:'问题',reply:'回复',requirements_changed:'要求变化',disagreement_changed:'分歧处理'};
 return <section aria-label="委派通信"><h4>沟通记录</h4><ol className="peer-messages">{d.messages.map(m=><li key={m.id}><strong>{m.change?'要求变更通知':m.from_user_id?(m.from_agent_id?`${name(m.from_agent_id)}（用户 ${m.from_user_id}）`:m.from_user_id===sessionUserID()?'你':`用户 ${m.from_user_id}`):name(m.from_agent_id||'系统')} → {name(m.to_agent_id)} · {kinds[m.kind]||'任务通知'}</strong><p>{m.change?`要求已变化：${m.change.changed_fields.map(f=>briefFieldLabel[f]||f).join('、')}。请核对依赖和版本。`:m.kind==='disagreement_changed'?'分歧记录已更新，请查看证据与后续责任。':m.kind==='task_completed'?'执行已结束，请核对交付和证据。':m.kind==='task_rejected'?'接收方拒绝了这项委派，请查看处理意见。':m.kind==='task_failed'?'执行失败，请查看处理记录。':m.kind==='task_cancelled'?'执行已停止，已完成的操作保留。':m.content}</p>{!!m.documents?.length&&<PeerSharedDocuments key={JSON.stringify(m.documents)} references={m.documents}/>} {m.reply_to_id&&<p className="subtle">回复：{d.messages.find(q=>q.id===m.reply_to_id)?.content||m.reply_to_id}</p>}<small className="subtle">需求 v{m.brief_version} / 约定 {m.agreement_revision||1} · {new Date(m.created_at).toLocaleString()} · {m.superseded?'已失效，后续执行不再接收':m.consumed_at||m.consumed_by_run_id?'已进入执行上下文':m.delivery_mode==='next_run'&&m.after_run_id?'等待当前运行结束后接收':'已送达收件箱，待执行接收'}{m.answered_by_id?' · 已回复':''}{!m.superseded&&(m.brief_version!==d.brief.version||(m.agreement_revision||1)!==(d.agreement_revision||1))?' · 历史要求下的消息':''}</small>{isOpenQuestion(m,d)&&<div><Button size="sm" variant="outline" onClick={()=>{setReplyTo(m.id);setKind('reply');setTo(m.from_agent_id||(m.to_agent_id===d.from_agent_id?d.to_agent_id:d.from_agent_id));}}>回复这条问题</Button></div>}</li>)}</ol>
 {d.messages_complete===false&&<p className="subtle">显示最近 128 条沟通记录。</p>}
 {!['cancelled','rejected','accepted_delivery'].includes(d.status)&&<form className="peer-form" onSubmit={send}><div className="todo-toolbar"><label>发送给<select aria-label="消息接收方" disabled={kind==='reply'} value={to} onChange={e=>setTo(e.target.value)}>{[d.to_agent_id,d.from_agent_id].map(id=><option key={id} value={id}>{name(id)}</option>)}</select></label><label>消息类型<select aria-label="消息类型" value={kind} onChange={e=>{setKind(e.target.value);if(e.target.value!=='reply')setReplyTo('');}}><option value="message">补充消息</option><option value="question">提出问题</option>{replyTo&&<option value="reply">回复问题</option>}</select></label><label>接收时机<select aria-label="消息接收时机" value={deliveryMode} onChange={e=>setDeliveryMode(e.target.value)}><option value="next_step">下一执行步骤</option><option value="next_run">当前运行结束后的下一轮</option></select></label></div>{reply&&<p>正在回复：{reply.content}</p>}<label>补充信息或讨论分歧<textarea required maxLength={8192} rows={3} value={message} onChange={e=>setMessage(e.target.value)}/></label>{d.access?.share&&<PeerDocumentPicker value={documents} disabled={busy} onChange={setDocuments}/>}<Button disabled={busy||kind==='reply'&&(!reply||!isOpenQuestion(reply,d))} type="submit">{documents.length&&d.access?.share?'发送消息并共享引用':kind==='reply'?'发送回复':kind==='question'?'发送问题':'发送消息'}</Button></form>}
 </section>;
}
